version: "3.4"

services:
  bcp-cms:
    # image: strapi/strapi:3.5.3
    container_name: bcp-cms
    restart: unless-stopped
    env_file: .env
    build:
      context: src/cms
      args:
        - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
        - ADMIN_USER=${ADMIN_USER}
        - ADMIN_PASSWORD=${ADMIN_PASSWORD}
        - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
        - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
        - ADMIN_EMAIL=${ADMIN_EMAIL}
        - API_TOKEN=${API_TOKEN}
        - API_USER_NAME=${API_USER_NAME}
        - API_USER_EMAIL=${API_USER_EMAIL}
        - API_USER_PASSWORD=${API_USER_PASSWORD}
        - DATABASE_HOST=${DATABASE_HOST}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_SSL=${DATABASE_SSL}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - REACT_APP_CMS_BASE_URL=${REACT_APP_CMS_BASE_URL}
    environment:
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ADMIN_FIRST_NAME: ${ADMIN_FIRST_NAME}
      ADMIN_LAST_NAME: ${ADMIN_LAST_NAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      API_TOKEN: ${API_TOKEN}
      API_USER_NAME: ${API_USER_NAME}
      API_USER_EMAIL: ${API_USER_EMAIL}
      API_USER_PASSWORD: ${API_USER_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_SSL: ${DATABASE_SSL}
      REACT_APP_CMS_BASE_URL: ${REACT_APP_CMS_BASE_URL}
    networks:
      - bcp-cms-network
    depends_on:
      - postgres
    ports:
      - "1337:1337"

  postgres:
    image: postgres:13.2
    container_name: bcp-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - bcp-cms-network
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

networks:
  bcp-cms-network:
    driver: bridge

volumes:
  local_postgres_data:
  website:
