{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-redis-secret" .Release.Name)) -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-redis-secret
  labels:
    component: {{ .Values.cms.componentName }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    "helm.sh/hook-weight": "0"
stringData:
  REDIS_PASSWORD: {{ randAlphaNum 50 | quote }}
{{- end -}}