airflow:
  uid: null
  gid: null
  executor: KubernetesExecutor

  webserver:

  statsd:
    enabled: false

  dags:
    persistence:
      enabled: true
      size: 1Gi
      storageClassName: netapp-file-standard
      accessMode: ReadWriteMany
    gitSync:
      enabled: false

  logs:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: netapp-file-standard
