apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: strapi
  namespace: 61d198-dev
spec:
  selector:
    app: bcparks-online
  replicas: 1
  template:
    metadata:
      labels:
        app: bcparks-online
    spec:
      containers:
        - name: strapi
          image: >-
            image-registry.openshift-image-registry.svc:5000/61d198-tools/strapi:dev
          ports:
            - containerPort: 1337
