version: "3.4"

services:
  react-frontend:
    container_name: bcp-frontend
    restart: unless-stopped
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
      REACT_APP_FRONTEND_BASE_URL: ${REACT_APP_FRONTEND_BASE_URL}
      PUBLIC_URL: ${PUBLIC_URL}
    networks:
      - bcp-cms-network
    volumes:
      - "./frontend:/app"
      - "./frontend/node_modules:/app/node_modules"
    ports:
      - "3000:3000"
    tty: true

  strapi:
    image: strapi/strapi:3.5.3
    container_name: bcp-strapi
    restart: unless-stopped
    env_file: .env
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
    networks:
      - bcp-cms-network
    depends_on:
      - postgres
    ports:
      - "1337:1337"

  postgres:
    image: postgres:13.2
    restart: always
    container_name: bcp-db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - bcp-cms-network
    volumes:
      - local_postgres_data:/var/lib/postgresql/data

networks:
  bcp-cms-network:
    driver: bridge

volumes:
  local_postgres_data:
