version: "3.4"

services:
  staging:
    container_name: bcp-staging
    restart: unless-stopped
    build:
      context: web
      dockerfile: Dockerfile   
    networks:
      - bcp-cms-network
    volumes:
      - "./web:/app"
      - "./web/node_modules:/app/node_modules"
      - website:/app/site
    ports:
      - "8000:8000"

  public:
    container_name: bcp-public
    restart: unless-stopped
    build:
      context: web
      dockerfile: Dockerfile-public    
    networks:
      - bcp-cms-network
    volumes:
      - website:/usr/local/nginx/html
    ports:
      - "80:80"

networks:
  bcp-cms-network:
    driver: bridge

volumes:
  website:
