name: Main-Build .NET API Image and Push to Openshift Registry
on:
  push:
    branches: [main, tools]
  workflow_dispatch:
    branches: [main, tools]
jobs:
  build-frontend:
    runs-on: ubuntu-20.04
    environment: Main
    env:
      VERSION: v1
      IMAGE_TAGS: latest
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      SERVICE_NAME: react-frontend
      IMAGE_NAME: frontend
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker repositories
        run: |
          docker login ${{secrets.REDHAT_REPO}} \
            -u ${{secrets.REDHAT_REPO_USER}} \
            -p '${{secrets.REDHAT_REPO_AUTH}}'
          docker login ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}} \
            -u ${{secrets.OPENSHIFT_SA_USERNAME}} \
            -p '${{secrets.OPENSHIFT_SA_PASSWORD}}'

      - name: Build the Frontend
        run: |
          echo "Building ${IMAGE_NAME}..."
          docker-compose build --force-rm --no-cache \
            --build-arg REACT_APP_API_BASE_URL=${{secrets.REACT_APP_API_BASE_URL}} \
            --build-arg REACT_APP_FRONTEND_BASE_URL=${{secrets.REACT_APP_FRONTEND_BASE_URL}} \
            --build-arg PUBLIC_URL=${{secrets.PUBLIC_URL}} \
            ${SERVICE_NAME}
          echo "Tagging ${IMAGE_NAME}..."
          docker tag \
            bcp-cms_${SERVICE_NAME} \
            ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_NAMESPACE}}/${IMAGE_NAME}
          echo "Pushing ${IMAGE_NAME}..."
          docker image push --all-tags \
            ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_NAMESPACE}}/${IMAGE_NAME}

  build-cms:
    runs-on: ubuntu-20.04
    environment: Main
    env:
      VERSION: v1
      IMAGE_TAGS: latest
      COMPOSE_DOCKER_CLI_BUILD: 1
      DOCKER_BUILDKIT: 1
      IMAGE_SOURCE: strapi/strapi
      IMAGE_NAME: strapi
      SERVICE_NAME: strapi
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker repositories
        run: |
          docker login ${{secrets.REDHAT_REPO}} \
            -u ${{secrets.REDHAT_REPO_USER}} \
            -p '${{secrets.REDHAT_REPO_AUTH}}'
          docker login ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}} \
            -u ${{secrets.OPENSHIFT_SA_USERNAME}} \
            -p '${{secrets.OPENSHIFT_SA_PASSWORD}}'
      - name: Build the CMS
        run: |          
          echo "Building ${IMAGE_NAME}..."
          docker-compose build --force-rm --no-cache \
            --build-arg DATABASE_HOST=${{secrets.DATABASE_HOST}} \
            --build-arg DATABASE_PORT=${{secrets.DATABASE_PORT}} \
            --build-arg DATABASE_NAME=${{secrets.DATABASE_NAME}} \
            --build-arg DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} \
            --build-arg DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} \
            --build-arg DATABASE_SSL=${{secrets.DATABASE_SSL}} \
            ${SERVICE_NAME}
          echo "Tagging ${IMAGE_NAME}..."
          docker tag ${IMAGE_SOURCE} \
            ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_NAMESPACE}}/${IMAGE_NAME}
          echo "Pushing ${IMAGE_NAME}..."
          docker image push --all-tags \
            ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_NAMESPACE}}/${IMAGE_NAME}
