name: Build Main Branch
on:
  push:
    branches: [main,tools]
  workflow_dispatch:
    branches: [main,tools]

jobs:
  build-frontend:
    runs-on: ubuntu-20.04
    environment: Main
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to RedHat
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.REDHAT_REPO}}
          username: ${{secrets.REDHAT_REPO_USER}}
          password: ${{secrets.REDHAT_REPO_AUTH}}

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/frontend
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/frontend:dev
          build-args:
            REACT_APP_API_BASE_URL={{secrets.REACT_APP_API_BASE_URL}}
            REACT_APP_CMS_BASE_URL={{secrets.REACT_APP_CMS_BASE_URL}}
            REACT_APP_FRONTEND_BASE_URL=${{secrets.REACT_APP_FRONTEND_BASE_URL}}
            REACT_APP_KEYCLOAK_AUTH_URL=${{secrets.REACT_APP_KEYCLOAK_AUTH_URL}}
            REACT_APP_KEYCLOAK_REALM=${{secrets.REACT_APP_KEYCLOAK_REALM}}
            REACT_APP_KEYCLOAK_CLIENT_ID=${{secrets.REACT_APP_KEYCLOAK_CLIENT_ID}}

  build-cms:
    runs-on: ubuntu-20.04
    environment: Main
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to RedHat
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.REDHAT_REPO}}
          username: ${{secrets.REDHAT_REPO_USER}}
          password: ${{secrets.REDHAT_REPO_AUTH}}

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/backend
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/strapi:dev
          build-args:
            DATABASE_HOST=${{secrets.DATABASE_HOST}}
            DATABASE_PORT=${{secrets.DATABASE_PORT}}
            DATABASE_NAME=${{secrets.DATABASE_NAME}}
            DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}
            DATABASE_PASSWORD=${{secrets.DATABASE_PASSWORD}} 
            DATABASE_SSL=${{secrets.DATABASE_SSL}}
            API_TOKEN=${{secrets.API_TOKEN}}
            API_USER_NAME=${{secrets.API_USER_NAME}}
            API_USER_EMAIL=${{secrets.API_USER_EMAIL}}
            API_USER_PASSWORD=${{secrets.API_USER_PASSWORD}}
 
  build-api:
    runs-on: ubuntu-20.04
    environment: Main
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to RedHat
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.REDHAT_REPO}}
          username: ${{secrets.REDHAT_REPO_USER}}
          password: ${{secrets.REDHAT_REPO_AUTH}}

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/api/BCParksApi
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/api:dev
 
  build-staging:
    runs-on: ubuntu-20.04
    environment: Main
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to OpenShift
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}
          username: ${{secrets.OPENSHIFT_SA_USERNAME}}
          password: ${{secrets.OPENSHIFT_SA_PASSWORD}}

      - name: Build and push
        uses: docker/build-push-action@v2.4.0
        with:
          context: ./src/web
          push: true
          tags: ${{secrets.OPENSHIFT_EXTERNAL_REPOSITORY}}/${{secrets.OPENSHIFT_LICENSE_PLATE}}-tools/staging:dev
